server:
#  port: 8111
   port: 0
spring:
  application:
    name: swcamp-user-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/menudb
    username: swcamp
    password: swcamp
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true

hello:
  message: Welcome to 19th SW-Camp

# 설명. 12시간의 만료 시간 + HMackSha 512 비밀키
#token:
#  expiration_time: 43200000
#  secret: 76I7DPQbwDax7GSljScAjt4kYg9V/BR5Getv8yvsUh9NoNnR4p+BE+0crGyk19//edd/ryYmNyAyuH+pn6xxnA==

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, beans, info
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

info:
  app:
    name: User Microservice
    description: This is a user microservice
    version: 1.0.0
  author: Yong Seung
  company: Ohgiraffers