server:
  port: 8761
eureka:
  client:

    # eureka server\uB294 eureka server\uC5D0\uC11C \uAD00\uB9AC \uD560 \uD544\uC694\uAC00 \uC5C6\uB2E4
    register-with-eureka: false

    # eureka server\uB294 \uB2E4\uB978 micro service\uB97C 30\uCD08 \uB2E8\uC704\uB85C \uC8FC\uAE30\uC801\uC73C\uB85C \uC778\uC9C0\uD560 \uD544\uC694\uAC00 \uC5C6\uB2E4.
    fetch-registry: false